worker1:
    build: .
    links:
        - redis1
        - bloom1
        - rethink1
        - gearman1
    volumes:
        - .:/code
    command: /bin/bash
    stdin_open: true
    tty: true
redis1:
    image: redis
    expose:
        - 6379
bloom1:
    image: saidimu/bloomd:v0.7.4
    expose:
        - 8673
    volumes:
        - bloomd_config:/etc/bloomd
rethink1:
    image: rethinkdb
    expose:
        - 28015
        - 29015
    ports:
        - "8080:8080"
    volumes:
        - rethinkdb_data:/data
# Just for replicating or sharding rethinkdb
# rethink2:
#     image: rethinkdb
#     links:
#         - rethink1
#     expose:
#         - 28015
#         - 29015
#     volumes:
#        - rethinkdb_data_2:/data
#     command: rethinkdb --join rethink1:29015 --bind all
gearman1:
    image: khanhicetea/gearmand_server:latest
    ports:
        - "4730:4730"
        - "4731:4731"
