bloomd_servers:
    - bloom1
redis_server:
    host: redis1
gearman_server:
    hosts:
        - 'gearman1:4730'
    max_tasks: 100
rethinkdb_server:
    host: rethink1
    port: 28015
    database: webcrawler
    tables:
        url_queue: url_queue
        raw_result: raw_result
        indexed_result: indexed_result
crawl_delay: 5
crawler_headers:
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'
    'accept': 'text/html,application/xhtml+xml;q=0.9,text/plain;q=0.8'
    'accept-language': 'en-US,en;q=0.8,vi;q=0.6'
    'accept-charset': 'utf-8'
